version: "3.9"
services:
  db:
    build: 
      context: ./database/
      dockerfile: db.Dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build: 
      context: ./api/
      dockerfile: api.Dockerfile
    networks:
      - frontend
      - backend

  frontend:
    build: 
      context: frontend/
      dockerfile: frontend.Dockerfile
    ports:
      - "8888:8888"
    stop_grace_period: 1m30s

networks:
  frontend:
  backend:

volumes:
  db-data: