version: "3.9"
services:
  db:
    build: database/db.Dockerfile
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build: api/api.Dockerfile
    networks:
      - frontend
      - backend

  frontend:
    build: frontend/frontend.Dockerfile
    ports:
      - "8888:8888"
    stop_grace_period: 1m30s

networks:
  frontend:
  backend:

volumes:
  db-data: